#!/bin/bash

sudo add-apt-repository -y universe
sudo add-apt-repository -y multiverse
sudo apt update

sudo dnf install -y ansible
sudo apt install -y ansible
sudo pamac install ansible
ansible-playbook -i hosts mysetup.playbook.yml
