---
- name: Install and set up all major applications on my system
  hosts: all
  become: true
  roles:
    - (mail)
    - firefox
    - git
    - (keystore)
    - Java
    - ZSH
    - kitty
    - tmux
    - i3
    - alsamixer
    - fehbg / nitrogen
    - lightdm
    - xrandr
    - vim
    - Okular

    - (IntelliJ)
    - (Clang / GCC)
    - (Visual Studio Code)
    - (docker)
    - (NodeJS)

