---
- name: Install and set up all major applications on my system
  hosts: all
  roles:
    - gnome
    - network
    - bluetooth
    - wayland
    - sway
    - themes
    - terminal
    - vim
    - firefox
    - okular
    - slack
    - thunderbird
    - dev
    - security

