---
- name: install sway
  become: True
  package:
    name: sway
    state: present
- name: "Enable eddsalkield/swaylock-effects module"
  become: True
  command: dnf copr enable -y eddsalkield/swaylock-effects
  args:
    warn: False
  register: result
  changed_when:
    - '"Enabling module streams" in result.stdout'
- name: install swaylock effects
  become: True
  dnf:
    enablerepo: eddsalkield/swaylock-effects
    name: swaylock-effects
    state: present
- name: install swayidle
  become: True
  package:
    name: swayidle
    state: present
- name: install wdisplays
  become: True
  package:
    name: wdisplays
    state: present
- name: install wofi
  become: True
  package:
    name: wofi
    state: present
- name: install waybar
  become: True
  package:
    name: waybar
    state: present
- name: install light
  become: True
  package:
    name: light
    state: present
- name: install Mako notification daemon
  become: True
  package:
    name: mako
    state: present
- name: install playerctl for media player control
  become: True
  package:
    name: playerctl
    state: present

