---
- name: install sway
  become: True
  package:
    name: sway
    state: present
- name: "Enable eddsalkield/swaylock-effects module"
  become: True
  command: dnf copr enable -y eddsalkield/swaylock-effects
  args:
    warn: False
  register: result
  changed_when:
    - '"Enabling module streams" in result.stdout'
- name: install swaylock effects
  become: True
  dnf:
    enablerepo: eddsalkield/swaylock-effects
    name: swaylock-effects
    state: present
- name: install swayidle
  become: True
  package:
    name: swayidle
    state: present
# display manager
- name: install wdisplays
  become: True
  package:
    name: wdisplays
    state: present
# menu and status bar
- name: install bemenu
  become: True
  package:
    name: bemenu
    state: present
- name: install waybar
  become: True
  package:
    name: waybar
    state: present
# screenshot utils
- name: install grim
  become: True
  package:
    name: grim
    state: present
- name: install slurp
  become: True
  package:
    name: slurp
    state: present
# brightness control for status bar
- name: install light
  become: True
  package:
    name: light
    state: present
# sound control for status bar
- name: install playerctl for media player control
  become: True
  package:
    name: playerctl
    state: present
# notification daemon and API
- name: install Mako notification daemon
  become: True
  package:
    name: mako
    state: present
- name: install libappindicator
  become: True
  package:
    name: libappindicator
    state: present
- name: install libappindicator for GTK
  become: True
  package:
    name: libappindicator-gtk3
    state: present

