---
- name: install CMake
  become: True
  package:
    name: cmake
    state: present
- name: install OpenJDK
  become: True
  package:
    name: openjdk-19-jdk
    state: present
- name: Install pv
  become: True
  package:
    name: pv
    state: present

- name: Install Netwide x86 Assembler
  become: True
  package:
    name: nasm
    state: present
- name: Install Python3
  become: True
  package:
    name: python3
    state: present
- name: Install Python3 pip
  become: True
  package:
    name: python3-pip
    state: present

